# Generated by Django 4.2.6 on 2023-11-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.URLField()),
                ('crawl_depth', models.IntegerField()),
                ('search_keywords', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_good_hit', models.BooleanField()),
                ('crawl_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawlrequest')),
            ],
        ),
    ]
